# -*- coding: utf-8 -*-
"""Operational REsearch Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMk1vfGNk7KZkYFkVCpmbJ9QJ91zM3zF
"""

# Commented out IPython magic to ensure Python compatibility.
import math
from datetime import datetime, timedelta

# %pip install cdsapi
# %pip install netcdf4
# %pip install cartopy
# %pip install cfgrib eccodes

import numpy as np
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import cdsapi
import xarray as xr
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns
import glob

# Inicializa a API do CDS com verificação SSL desativada
client = cdsapi.Client(url='https://ads.atmosphere.copernicus.eu/api', key='56ff124d-08b8-4fe3-a524-e45272516d72', verify=False)

dataset = "cams-gridded-solar-radiation"
request = {
    "variable": ["global_horizontal_irradiation"],
    "sky_type": ["clear"],
    "version": ["4.6"],
    "year": ["2022"],
    "month": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12"
    ],
    "area": [51.0, -5, 42.0, 8.0]

}
client.retrieve(dataset, request).download()

# -------------------------------------------------
# 1️Combine every year
# -------------------------------------------------
files = sorted(glob.glob("v4.6_GHI_clear_2022_*.nc"))

ds = xr.open_mfdataset(
    files,
    combine="by_coords",
    engine="h5netcdf",
    chunks={"time": 1000}   # 👈 adjust chunk size
)

ghi_sum = (
    ds["global_horizontal_clear_sky_irradiation"]
    .sum(dim="time")
)

ghi_energy = ghi_sum * 0.25

ghi_energy = (
    ds["global_horizontal_clear_sky_irradiation"]
    .sum(dim="time")
    .compute()   # only this result is loaded
)

ds = ds.astype("float32")

ds["global_horizontal_clear_sky_irradiation"].sum(dim="time")

df_sum = ghi_energy.to_dataframe(name="GHI_energy_Wh_m2").reset_index()

ghi_grid = df_sum.pivot(
    index="latitude",
    columns="longitude",
    values="GHI_energy_Wh_m2"
)
df_sum

# CODE POUR IRRADIATION HEAT MAP
plt.figure(figsize=(12,8))
sns.heatmap(
    ghi_grid[::-1],  # inverse les lignes pour que le Sud soit en bas
    cmap="YlOrRd",
    cbar_kws={'label': 'GHI cumulative (Wh/m²)'}
)
plt.title("Global Horizontal Irradiation (Cumulative)")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.show()

# CODE POUR IRRADIATION HEATMAP + CARTE DES PAYS
# Zone CAMS
lat_min, lat_max = 42.0, 51.0
lon_min, lon_max = -5.0, 8.0

plt.figure(figsize=(18,10))

# Axe géographique Cartopy
ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_extent([lon_min, lon_max, lat_min, lat_max], crs=ccrs.PlateCarree())

# Ajouter carte
ax.add_feature(cfeature.LAND, facecolor='lightgray')
ax.add_feature(cfeature.BORDERS, edgecolor='black')
ax.add_feature(cfeature.COASTLINE)

# -----------------------
# Heatmap CAMS
# -----------------------
# Créer les coordonnées exactes de la grille
lon = np.array(sorted(ghi_grid.columns))
lat = np.array(sorted(ghi_grid.index))  # latitudes croissantes

# Meshgrid pour imshow
Lon, Lat = np.meshgrid(lon, lat)

# Afficher la heatmap
pcm = ax.pcolormesh(
    Lon, Lat, ghi_grid.values,  # pas besoin d'inverser
    cmap='YlOrRd',
    alpha=1,
    shading='auto'              # très important pour que les pixels correspondent
)

# Ajouter colorbar
plt.colorbar(pcm, ax=ax, label='GHI cumulative (Wh/m²)')

# Axes et titre
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("Global Horizontal Irradiation (Cumulative) over France")
plt.show()

#CODE POUR TEMPERATURE

# Inicializa a API do CDS com verificação SSL desativada
c = cdsapi.Client(url='https://ads.atmosphere.copernicus.eu/api', key='56ff124d-08b8-4fe3-a524-e45272516d72', verify=False)



dataset = "cams-global-reanalysis-eac4-monthly"
request = {
    "variable": ["2m_temperature"],
    "year": ["2022"],
    "month": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12"
    ],
    "product_type": ["monthly_mean"],
    "data_format": "grib",
    "area": [51.0, -5, 42.0, 8.0]
}

c.retrieve(dataset, request).download()

ds = xr.open_dataset(
    "fc76e33400e82ede347d0eac8828ded4.grib",
    engine="cfgrib"
)

ds

# Annual mean over time (removes the time dimension)
t2m_annual_mean = ds["t2m"].mean(dim="time")

# Convert from Kelvin to Celsius
t2m_annual_mean_c = t2m_annual_mean - 273.15

# Convert to DataFrame
df_t2m_annual = (
    t2m_annual_mean_c
    .to_dataframe(name="T2m_mean_annual_C")
    .reset_index()
)

df_t2m_annual

# Create pivot grid: latitudes as index, longitudes as columns
t2m_grid = df_t2m_annual.pivot(
    index="latitude",
    columns="longitude",
    values="T2m_mean_annual_C"
)

# Sort axes (South → North, West → East)
t2m_grid = t2m_grid[sorted(t2m_grid.columns)]      # longitudes increasing
t2m_grid = t2m_grid.sort_index(ascending=True)    # latitudes increasing
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 8))
sns.heatmap(
    t2m_grid[::-1],          # invert rows so South is at the bottom
    cmap="coolwarm",         # blue (cold) → red (hot)
    cbar_kws={'label': 'Annual mean temperature (°C)'}
)

plt.title("Annual Mean 2m Temperature (2022)")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.show()

# CAMS area
lat_min, lat_max = 42.0, 51.0
lon_min, lon_max = -5.0, 8.0

plt.figure(figsize=(18, 10))

# Geographic axis (Cartopy)
ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_extent([lon_min, lon_max, lat_min, lat_max], crs=ccrs.PlateCarree())

# Add map features
ax.add_feature(cfeature.LAND, facecolor='lightgray')
ax.add_feature(cfeature.BORDERS, edgecolor='black')
ax.add_feature(cfeature.COASTLINE)

# -----------------------
# Temperature heatmap
# -----------------------
# Create exact grid coordinates
lon = np.array(sorted(t2m_grid.columns))
lat = np.array(sorted(t2m_grid.index))  # latitudes increasing

# Meshgrid for pcolormesh
Lon, Lat = np.meshgrid(lon, lat)

# Plot temperature heatmap
pcm = ax.pcolormesh(
    Lon, Lat, t2m_grid.values,
    cmap="coolwarm",        # blue (cold) → red (hot)
    alpha=1,
    shading="auto"
)

# Colorbar
plt.colorbar(pcm, ax=ax, label="Annual mean temperature (°C)")

# Labels and title
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("Annual Mean 2m Temperature (2022) over France")

plt.show()

# Convert annual mean temperature from °C to K
df_t2m_annual["T2m_mean_annual_K"] = (
    df_t2m_annual["T2m_mean_annual_C"] + 273.15
)

# Apply the formula: -0.35 * (T - (273 + 25))
df_t2m_annual["temp_factor"] = (
    -0.35 * (df_t2m_annual["T2m_mean_annual_K"] - (273 + 25))
)

df_t2m_annual

# Interpoler la température sur la grille GHI
t2m_on_ghi_grid = t2m_annual_mean_c.interp(
    latitude=ghi_energy.latitude,
    longitude=ghi_energy.longitude,
    method="nearest"
)

t2m_on_ghi_grid

temp_factor_on_ghi = -0.35 * (
    (t2m_on_ghi_grid + 273.15) - (273 + 25)
)

GHI_temp_corrected = ghi_energy * temp_factor_on_ghi

df_final = (
    GHI_temp_corrected
    .to_dataframe(name="GHI_temp_corrected")
    .reset_index()
)

df_final

# CAMS area
lat_min, lat_max = 42.0, 51.0
lon_min, lon_max = -5.0, 8.0

plt.figure(figsize=(18, 10))

# Geographic axis (Cartopy)
ax = plt.axes(projection=ccrs.PlateCarree())
ax.set_extent([lon_min, lon_max, lat_min, lat_max], crs=ccrs.PlateCarree())

# Add map features
ax.add_feature(cfeature.LAND, facecolor='lightgray')
ax.add_feature(cfeature.BORDERS, edgecolor='black')
ax.add_feature(cfeature.COASTLINE)

# -----------------------
# Heatmap GHI corrected
# -----------------------
# Create exact grid coordinates
lon = np.array(sorted(df_final['longitude'].unique()))
lat = np.array(sorted(df_final['latitude'].unique()))  # latitudes increasing

# Pivot dataframe to grid
ghi_temp_grid = df_final.pivot(index='latitude', columns='longitude', values='GHI_temp_corrected')
ghi_temp_grid = ghi_temp_grid[sorted(ghi_temp_grid.columns)]
ghi_temp_grid = ghi_temp_grid.sort_index(ascending=True)

# Meshgrid for pcolormesh
Lon, Lat = np.meshgrid(lon, lat)

# Plot heatmap with a nicer color
pcm = ax.pcolormesh(
    Lon, Lat, ghi_temp_grid.values,
    cmap="viridis",          # bleu → vert → jaune
    alpha=1,
    shading="auto"
)
plt.colorbar(pcm, ax=ax, label="GHI × Temp Factor (Wh/m²)")


# Labels and title
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("GHI Corrected by Temperature (Annual, 2022)")

plt.show()