# -*- coding: utf-8 -*-
"""USMB_solar_project_panel_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/rjlobosco/usmb_26/blob/main/USMB_solar_project_panel_detection.ipynb
"""

!pip install roboflow
!pip install ultralytics

from roboflow import Roboflow
from ultralytics import YOLO

!pip install roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="buMGF1FhJBQTVvngwajD")
project = rf.workspace("myprojects-20ycu").project("usmb-3ou0v")
version = project.version(1)
dataset = version.download("yolov11")

import os
from ultralytics import YOLO # Ensure YOLO is imported

# carregar modelo
#model = YOLO("yolo11l-seg.pt") # Initialize the model
model =YOLO("yolo11s-seg.pt")
# treinar
model.train(
    data=os.path.join(dataset.location, "data.yaml"),
    epochs=2,         # mais épocas para convergência melhor
    imgsz=416,         # imagens maiores para detalhes
    batch=4,           # aproveitando os 16GB da GPU
    workers=8,          # pode aumentar se sua máquina tiver muitos núcleos
    project="usmb-3ou0v",
    name="exp_highres"
)